{
 "title": "Asset Performance",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "NodeID", "query": "Select NodeID From DeviceData" },
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "220" }
  ]
 },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\n/*sum(CountGood)*1.0/(sum(CountGood)+sum(CountBad)) AS Quality,\r\n(sum(CountGood)+sum(CountBad))*1.0/$idealRunrate AS Performaance,\r\nSUM(Frequency)*1.0/60 AS Availability,*/\r\n(SUM(TimeOn)*1.0/60)*((sum(CountGood)+sum(CountBad))*1.0/$idealRunrate)*(ISNULL((sum(CountGood)*1.0)/NULLIF((sum(CountGood)+sum(CountBad)),0),0)) AS OEE\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, RunningStatus, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "OEE Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\nISNULL((sum(CountGood)*1.0)/NULLIF((sum(CountGood)+sum(CountBad)),0),0) AS Quality,\r\n(sum(CountGood)+sum(CountBad))*1.0/$idealRunrate AS Performaance,\r\nSUM(TimeOn)*1.0/60 AS Availability\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, RunningStatus, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\n/*COUNT(RunningStatus) AS RunningStatusCount,*/\r\nSUM(TimeOn)*1.0/60 AS MachineOn\r\n/*SUM(TimeOff)*1.0/60 AS MachineOff*/\r\nFROM dbo.DeviceData\r\nWHERE SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, TimeOn, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\n/*COUNT(RunningStatus) AS RunningStatusCount,*/\r\nSUM(TimeOn) AS 'MachineOn'\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, TimeOn, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\n/*COUNT(RunningStatus) AS RunningStatusCount,*/\r\nSUM(TimeOff) AS 'MachineOff'\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, TimeOff, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  MIN(SourceTimestamp) AS time,\r\nNodeID, \r\nISNULL((sum(CountGood)*1.0)/NULLIF((sum(CountGood)+sum(CountBad)),0),0) AS Quality\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Quality Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\nNodeID, \r\nsum(CountGood) AS CountGood,\r\nsum(CountBad) AS CountBad,\r\nsum(CountGood)+sum(CountBad) AS Total\r\nFROM dbo.DeviceData\r\nWHERE SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  MIN(SourceTimestamp) AS time,\r\nNodeID, \r\n(sum(CountGood)+sum(CountBad))*1.0/$idealRunrate AS Performance\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Performance Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  \r\nMIN(SourceTimestamp) AS time,\r\n1.0*$idealRunrate AS 'Target Run Rate',\r\nsum(CountGood)+Sum(CountBad) As 'Actual Run Rate'\r\nFROM dbo.DeviceData\r\nwhere SourceTimestamp BETWEEN $__timeFrom() and $__timeTo() and NodeID = '$NodeID'\r\nGROUP BY NodeID, dateadd(minute,(datediff(minute,0,SourceTimestamp)/1)*1,0)\r\nORDER BY Time"
    }
   ]
  }
 ]
}